M48
; DRILL file {KiCad 7.0.8-7.0.8~ubuntu22.04.1} date Do 30 Nov 2023 18:16:24 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-30T18:16:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8-7.0.8~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
%
G90
G05
T1
X4.9059Y-5.2323
X5.1335Y-5.2323
T2
X4.7622Y-4.4246
X4.7622Y-4.5046
X4.9622Y-4.4646
T0
M30
