#pragma once

#include <stdint.h>

#define FF_FLASH_TOTAL_SIZE		2097152
#define FF_FLASH_SECTOR_SIZE	4096

#define FF_FLASH_DISKS			2
// DISK0 is writable
#define FF_FLASH_DISK0_SIZE		1048576
#define FF_FLASH_DISK1_SIZE		1048576

#define FF_FLASH_DISK0_SECTORS	(FF_FLASH_DISK0_SIZE / FF_FLASH_SECTOR_SIZE)
#define FF_FLASH_DISK1_SECTORS	(FF_FLASH_DISK1_SIZE / FF_FLASH_SECTOR_SIZE)

static_assert(FF_FLASH_DISK0_SIZE + FF_FLASH_DISK1_SIZE <= FF_FLASH_TOTAL_SIZE);
static_assert(FF_FLASH_DISK0_SIZE % FF_FLASH_SECTOR_SIZE == 0);
static_assert(FF_FLASH_DISK1_SIZE % FF_FLASH_SECTOR_SIZE == 0);

